### ISSUE TITLE
Add a directory to `dotfiles_files`

### ISSUE THREAD

**Issue by ticklepoke** [geerlingguy/ansible-role-dotfiles#22]
## Use Case

Some configs can be spread across multiple files in a folder. For example, neovim configs can consist an `init.vim` or `init.lua` and multiple other `.vim` or `.lua` files. It would be useful if we can track the entire folder with a wildcard:

```yml
dotfiles_files:
  - .config/nvim/*
```

**Comment by ticklepoke** [comment]
Solved, we can just do 

```yml
dotfiles_files:
  - .config/nvim/
```

I believe we still need a task to handle vim plugins, something like [this](https://gist.github.com/snahor/de8b13a9fa19c8c581460a198c7f1d14).

**Comment by tgallacher** [comment]
hey @ticklepoke I can't seem to get this to work. The symlink part seems to fail with `No such file or directory`, even though everything is where it needs to be. 

The error seems to be the trailing slash on the `dest` key in the symlink. See [this StackOverflow issue](https://stackoverflow.com/a/54714460). 

Any thoughts on a workaround?

Using Ansible `v2.13.3`
Python `v3.10.6`

**Comment by tgallacher** [comment]
> hey @ticklepoke I can't seem to get this to work. The symlink part seems to fail with `No such file or directory`, even though everything is where it needs to be.
> 
> The error seems to be the trailing slash on the `dest` key in the symlink. See [this StackOverflow issue](https://stackoverflow.com/a/54714460).
> 
> Any thoughts on a workaround?
> 
> Using Ansible `v2.13.3` Python `v3.10.6`

Seems leaving the trailing slash actually fixes this. So

```yaml
dotfiles_files:
  - .config/nvm
```
