### ISSUE TITLE
Support filenames without leading `.`

### ISSUE THREAD

**Issue by fwilhe** [geerlingguy/ansible-role-dotfiles#7]
I like to keep my dotfiles without the leading dot in my git repository. It would be nice if this role could handle this when creating the links, so for example `vimrc` in the git repo should be linked to `~/.vimrc`.

**Comment by fubarhouse** [comment]
Old issue I know, but something came up here.

Looking at this role, it doesn't explicitly check if a file is a dotfile.

The following will work, but it'll still implement the files as symlinks to the configured directory.

````
dotfiles_files:
  - my_bash_profile
  - my_shell_profile
  - my_zsh_profile
````

**Comment by opdavies** [comment]
> The following will work, but it'll still implement the files as symlinks to the configured directory.

Yes, it will symlink them, but it won't add the required period at the beginning of the filename. If I create a file called `test`, it will be symlinked as `test` rather than `.test`.

**Comment by opdavies** [comment]
Alternatively I can suggest using `rcm` and https://github.com/karlmdavis/ansible-role-rcm-dotfiles which supports filenames without the leading `.`, as well as other features like tagging/grouping related dotfiles.
