### ISSUE TITLE
DEPRECATION WARNING: always_run is deprecated

### ISSUE THREAD

**Issue by jpartain89** [geerlingguy/ansible-role-dotfiles#8]
Obviously, this needs to be updated.... 

```
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

The specific section is:

```
- name: Ensure all configured dotfiles are links.
  shell: "ls -F {{ dotfiles_home }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  always_run: yes
  changed_when: false
  with_items: "{{ dotfiles_files }}"
```

**Comment by emielmolenaar** [comment]
https://github.com/geerlingguy/ansible-role-dotfiles/commit/9c2d0cf8f1818786391606fadb5d98eb3ba04016

**Comment by jpartain89** [comment]
While he might've updated the code, a new release has to be pushed out in order for Ansible-Galaxy to see it and our `ansible-galaxy` based installations of these roles to get the update....

**Comment by geerlingguy** [comment]
Fixed via https://github.com/geerlingguy/ansible-role-dotfiles/pull/9, in 1.2.0.
